package Modelos

import java.sql.Connection
import java.sql.DriverManager

class Conexion {

    fun cadenaConexion(): Connection?{
        try {
            val ipSofi = "jdbc:oracle:thin:@172.24.192.1:1521:xe"
           val ipRuth = "jdbc:oracle:thin:@192.168.3.8:1521:xe"
            val usuario = "Ruth_Sofi"
            val contrasena = "ricaldone2024e"

            val conexion = DriverManager.getConnection(ipSofi, usuario, contrasena)
            return conexion
        }catch (e: Exception){
            println("Este es el error: $e")
            return null
        }
    }

    /*
    --------TABLAS DE ORACLE----------

  CREATE TABLE Pacientes (
    id_paciente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombres VARCHAR2(100),
    apellidos VARCHAR2(100),
    enfermedad VARCHAR2(100),
    numero_habitacion VARCHAR2(10),
    numero_cama VARCHAR2(10),
    fecha_nacimiento INT
  );

  CREATE TABLE Medicamentos (
    id_medicamento NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_medicamento VARCHAR2(100) NOT NULL
  );

  CREATE TABLE SuministroMedicamentos (
    id_suministro NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente NUMBER NOT NULL,
    id_medicamento NUMBER NOT NULL,
    hora_aplicacion TIMESTAMP NOT NULL,
    CONSTRAINT FKid_paciente FOREIGN KEY (id_paciente) REFERENCES Pacientes(id_paciente),
    CONSTRAINT FKid_medicamento FOREIGN KEY (id_medicamento) REFERENCES Medicamentos(id_medicamento)
  );




     */
}